version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
      
  prometheus:
      image: bitnami/prometheus:latest
      container_name: prometheus
      hostname: prometheus
      restart: always
      volumes:
          - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml 
      ports:
          - "9090:9090"